export default {
  COLOR_BPM: 0x03C04A,
  COLOR_BACKGROUND: 0x000000,
  COLOR_LANE_PRIMARY: 0xFFFFFF,
  COLOR_LANE_SECONDARY: 0x4C3B5C,
  COLOR_BAR_PRIMARY: 0xFFFFFF,
  COLOR_BAR_SECONDARY: 0xCCCCCC,
  COLOR_PLAYHEAD: 0xFF153F,
  COLOR_SLIDE_PATH: 0xFFFCCC,
  ALPHA_SLIDE_PATH: 0.95,
  COLOR_SLIDE_PATH_CRITICAL: 0xDAFDF0
}