// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ja'

export type Locales =
	| 'en'
	| 'ja'
	| 'zh'

export type Translation = {
	'editor': {	
		'menu': {	
			/**
			 * ファイル (&F)
			 */
			'file': string
			/**
			 * ライブラリ (&L)
			 */
			'library': string
			/**
			 * 編集 (&E)
			 */
			'edit': string
			/**
			 * 設定 (&P)
			 */
			'preferences': string
			/**
			 * ヘルプ (&H)
			 */
			'help': string
			/**
			 * 新規 (&N)
			 */
			'new': string
			/**
			 * 開く (&O)
			 */
			'open': string
			/**
			 * 譜面保存 (&S)
			 */
			'save': string
			/**
			 * 画像出力 (&I)
			 */
			'image': string
			/**
			 * 元に戻す (&U)
			 */
			'undo': string
			/**
			 * やり直し (&R)
			 */
			'redo': string
			/**
			 * すべて選択 (&A)
			 */
			'selectall': string
			/**
			 * 切り取り (&X)
			 */
			'cut': string
			/**
			 * コピー (&C)
			 */
			'copy': string
			/**
			 * 貼り付け (&P)
			 */
			'paste': string
			/**
			 * 一覧 (&A)
			 */
			'listall': string
			/**
			 * アップロード (&U)
			 */
			'upload': string
			/**
			 * 言語 (&G)
			 */
			'language': string
			/**
			 * リネーム (&R)
			 */
			'rename': string
			/**
			 * 削除 (&D)
			 */
			'delete': string
			/**
			 * すべて削除 (&A)
			 */
			'deleteall': string
			/**
			 * 複製 (&D)
			 */
			'duplicate': string
			/**
			 * 左右反転 (&H)
			 */
			'flip': string
			/**
			 * 直線 (&S)
			 */
			'straight': string
			/**
			 * 加速 (&I)
			 */
			'curvein': string
			/**
			 * 減速 (&O)
			 */
			'curveout': string
			/**
			 * 可視 (&B)
			 */
			'visible': string
			/**
			 * 不可視 (&N)
			 */
			'invisible': string
			/**
			 * 無視 (&G)
			 */
			'ignored': string
			/**
			 * 縮める (&K)
			 */
			'shrink': string
			/**
			 * ダウンロード (&U)
			 */
			'download': string
		}
		'menuDescription': {	
			/**
			 * 新規譜面を作成
			 */
			'new': string
			/**
			 * 譜面一覧を開く
			 */
			'open': string
			/**
			 * SUSファイルに出力
			 */
			'save': string
			/**
			 * 譜面の画像化
			 */
			'image': string
			/**
			 * 前の操作を取り消す
			 */
			'undo': string
			/**
			 * 取り消した操作をやり直す
			 */
			'redo': string
			/**
			 * すべてのノーツを選択
			 */
			'selectall': string
		}
		'panel': {	
			/**
			 * （小節）
			 */
			'measure': string
			/**
			 * 合計コンボ数 {combo}
			 * @param {unknown} combo
			 */
			'totalcombo': RequiredParams1<'combo'>
			/**
			 * 選択されたノーツ数 {selected}
			 * @param {unknown} selected
			 */
			'totalselected': RequiredParams1<'selected'>
			/**
			 * 頭出し
			 */
			'skipstart': string
			/**
			 * 再生／一時停止
			 */
			'playpause': string
			/**
			 * 戻る
			 */
			'skipback': string
			/**
			 * スクロール方式
			 */
			'scrollmode': string
			/**
			 * 基本情報
			 */
			'metadata': string
			/**
			 * タイトル
			 */
			'title': string
			/**
			 * アーティスト
			 */
			'artist': string
			/**
			 * 譜面作者
			 */
			'author': string
			/**
			 * 統計
			 */
			'statistics': string
			/**
			 * 履歴
			 */
			'history': string
			/**
			 * 元に戻す
			 */
			'undo': string
			/**
			 * やり直し
			 */
			'redo': string
			/**
			 * 開く
			 */
			'open': string
			/**
			 * マスター音量
			 */
			'master': string
			/**
			 * SE音量
			 */
			'sfxvolume': string
			/**
			 * 音楽情報
			 */
			'music': string
			/**
			 * 音楽ファイル
			 */
			'musicfile': string
			/**
			 * コントロール
			 */
			'control': string
			/**
			 * 更新時刻
			 */
			'updatedTime': string
		}
		'scrollmode': {	
			/**
			 * 上下スクロール
			 */
			'page': string
			/**
			 * 固定スクロール
			 */
			'smooth': string
			/**
			 * スクロールしない
			 */
			'none': string
		}
		'messages': {	
			/**
			 * 数値を入力してください
			 */
			'nonNumeralInputError': string
			/**
			 * {from}から{to}までの数値を入力してください
			 * @param {number} from
			 * @param {number} to
			 */
			'outOfRangeInputError': RequiredParams2<'from', 'to'>
			/**
			 * {project} として保存されました。
			 * @param {string} project
			 */
			'projectSavedAs': RequiredParams1<'project'>
			/**
			 * SUSファイルを読み込む際にエラーが発生しました
			 */
			'loadingSUSError': string
			/**
			 * 譜面が自動保存されました
			 */
			'autoSaved': string
			/**
			 * 譜面が保存されました
			 */
			'saved': string
			/**
			 * アップロードするノーツが選択されていません
			 */
			'uploadNotSelectedError': string
			/**
			 * タイトルを入力してください
			 */
			'inputTitlePrompt': string
			/**
			 * 説明を入力してください
			 */
			'inputDescriptionPrompt': string
			/**
			 * タイトルや説明を入力してください
			 */
			'inputEmptyError': string
			/**
			 * アップロードしました
			 */
			'uploaded': string
			/**
			 * アップロードに失敗しました
			 */
			'uploadFailed': string
			/**
			 * 本当にエディターを閉じますか
			 */
			'exitConfirm': string
			/**
			 * 不明なファイルタイプです
			 */
			'unknownFileType': string
			/**
			 * ライブラリの読み込みに失敗しました。
			 */
			'loadingLibraryFailed': string
			/**
			 * 設定を保存しました
			 */
			'preferencesSaved': string
			/**
			 * 本当に削除しますか？
			 */
			'deleteConfirm': string
		}
		'snapTo': {	
			/**
			 * {n}分音符
			 * @param {number} n
			 */
			'snap': RequiredParams1<'n'>
			/**
			 * 分音符（1 ~ 1920）
			 */
			'snapWithRange': string
			/**
			 * カスタム
			 */
			'custom': string
		}
		'mutation': {	
			/**
			 * 更新
			 */
			'update': string
			/**
			 * カット
			 */
			'cut': string
			/**
			 * 削除
			 */
			'delete': string
			/**
			 * 反転
			 */
			'flip': string
			/**
			 * 移動
			 */
			'move': string
			/**
			 * リサイズ
			 */
			'resize': string
		}
		'dialog': {	
			/**
			 * BPM設定
			 */
			'bpmTitle': string
			/**
			 * カスタム分音符
			 */
			'customSnappingTitle': string
			/**
			 * 画像出力
			 */
			'imageTitle': string
			/**
			 * ライブラリ
			 */
			'libraryTitle': string
			/**
			 * 環境設定
			 */
			'preferencesTitle': string
			/**
			 * 譜面一覧
			 */
			'projectsTitle': string
			/**
			 * 追加
			 */
			'append': string
			/**
			 * 変更
			 */
			'change': string
			/**
			 * 出力
			 */
			'export': string
			/**
			 * OK
			 */
			'ok': string
			/**
			 * 新規作成
			 */
			'new': string
			/**
			 * SUSファイルを開く
			 */
			'opensus': string
		}
		'preferences': {	
			/**
			 * 自動保存の間隔（秒）
			 */
			'autosaveInterval': string
			/**
			 * スクロールの早さ（倍）
			 */
			'scrollSpeed': string
		}
		'modes': {	
			/**
			 * 選択
			 */
			'select': string
			/**
			 * タップ
			 */
			'tap': string
			/**
			 * スライド
			 */
			'slide': string
			/**
			 * 中継点
			 */
			'mid': string
			/**
			 * フリック
			 */
			'flick': string
			/**
			 * クリティカル
			 */
			'critical': string
			/**
			 * BPM
			 */
			'bpm': string
		}
	}
}

export type TranslationFunctions = {
	'editor': {	
		'menu': {	
			/**
			 * ファイル (&F)
			 */
			'file': () => LocalizedString
			/**
			 * ライブラリ (&L)
			 */
			'library': () => LocalizedString
			/**
			 * 編集 (&E)
			 */
			'edit': () => LocalizedString
			/**
			 * 設定 (&P)
			 */
			'preferences': () => LocalizedString
			/**
			 * ヘルプ (&H)
			 */
			'help': () => LocalizedString
			/**
			 * 新規 (&N)
			 */
			'new': () => LocalizedString
			/**
			 * 開く (&O)
			 */
			'open': () => LocalizedString
			/**
			 * 譜面保存 (&S)
			 */
			'save': () => LocalizedString
			/**
			 * 画像出力 (&I)
			 */
			'image': () => LocalizedString
			/**
			 * 元に戻す (&U)
			 */
			'undo': () => LocalizedString
			/**
			 * やり直し (&R)
			 */
			'redo': () => LocalizedString
			/**
			 * すべて選択 (&A)
			 */
			'selectall': () => LocalizedString
			/**
			 * 切り取り (&X)
			 */
			'cut': () => LocalizedString
			/**
			 * コピー (&C)
			 */
			'copy': () => LocalizedString
			/**
			 * 貼り付け (&P)
			 */
			'paste': () => LocalizedString
			/**
			 * 一覧 (&A)
			 */
			'listall': () => LocalizedString
			/**
			 * アップロード (&U)
			 */
			'upload': () => LocalizedString
			/**
			 * 言語 (&G)
			 */
			'language': () => LocalizedString
			/**
			 * リネーム (&R)
			 */
			'rename': () => LocalizedString
			/**
			 * 削除 (&D)
			 */
			'delete': () => LocalizedString
			/**
			 * すべて削除 (&A)
			 */
			'deleteall': () => LocalizedString
			/**
			 * 複製 (&D)
			 */
			'duplicate': () => LocalizedString
			/**
			 * 左右反転 (&H)
			 */
			'flip': () => LocalizedString
			/**
			 * 直線 (&S)
			 */
			'straight': () => LocalizedString
			/**
			 * 加速 (&I)
			 */
			'curvein': () => LocalizedString
			/**
			 * 減速 (&O)
			 */
			'curveout': () => LocalizedString
			/**
			 * 可視 (&B)
			 */
			'visible': () => LocalizedString
			/**
			 * 不可視 (&N)
			 */
			'invisible': () => LocalizedString
			/**
			 * 無視 (&G)
			 */
			'ignored': () => LocalizedString
			/**
			 * 縮める (&K)
			 */
			'shrink': () => LocalizedString
			/**
			 * ダウンロード (&U)
			 */
			'download': () => LocalizedString
		}
		'menuDescription': {	
			/**
			 * 新規譜面を作成
			 */
			'new': () => LocalizedString
			/**
			 * 譜面一覧を開く
			 */
			'open': () => LocalizedString
			/**
			 * SUSファイルに出力
			 */
			'save': () => LocalizedString
			/**
			 * 譜面の画像化
			 */
			'image': () => LocalizedString
			/**
			 * 前の操作を取り消す
			 */
			'undo': () => LocalizedString
			/**
			 * 取り消した操作をやり直す
			 */
			'redo': () => LocalizedString
			/**
			 * すべてのノーツを選択
			 */
			'selectall': () => LocalizedString
		}
		'panel': {	
			/**
			 * （小節）
			 */
			'measure': () => LocalizedString
			/**
			 * 合計コンボ数 {combo}
			 */
			'totalcombo': (arg: { combo: unknown }) => LocalizedString
			/**
			 * 選択されたノーツ数 {selected}
			 */
			'totalselected': (arg: { selected: unknown }) => LocalizedString
			/**
			 * 頭出し
			 */
			'skipstart': () => LocalizedString
			/**
			 * 再生／一時停止
			 */
			'playpause': () => LocalizedString
			/**
			 * 戻る
			 */
			'skipback': () => LocalizedString
			/**
			 * スクロール方式
			 */
			'scrollmode': () => LocalizedString
			/**
			 * 基本情報
			 */
			'metadata': () => LocalizedString
			/**
			 * タイトル
			 */
			'title': () => LocalizedString
			/**
			 * アーティスト
			 */
			'artist': () => LocalizedString
			/**
			 * 譜面作者
			 */
			'author': () => LocalizedString
			/**
			 * 統計
			 */
			'statistics': () => LocalizedString
			/**
			 * 履歴
			 */
			'history': () => LocalizedString
			/**
			 * 元に戻す
			 */
			'undo': () => LocalizedString
			/**
			 * やり直し
			 */
			'redo': () => LocalizedString
			/**
			 * 開く
			 */
			'open': () => LocalizedString
			/**
			 * マスター音量
			 */
			'master': () => LocalizedString
			/**
			 * SE音量
			 */
			'sfxvolume': () => LocalizedString
			/**
			 * 音楽情報
			 */
			'music': () => LocalizedString
			/**
			 * 音楽ファイル
			 */
			'musicfile': () => LocalizedString
			/**
			 * コントロール
			 */
			'control': () => LocalizedString
			/**
			 * 更新時刻
			 */
			'updatedTime': () => LocalizedString
		}
		'scrollmode': {	
			/**
			 * 上下スクロール
			 */
			'page': () => LocalizedString
			/**
			 * 固定スクロール
			 */
			'smooth': () => LocalizedString
			/**
			 * スクロールしない
			 */
			'none': () => LocalizedString
		}
		'messages': {	
			/**
			 * 数値を入力してください
			 */
			'nonNumeralInputError': () => LocalizedString
			/**
			 * {from}から{to}までの数値を入力してください
			 */
			'outOfRangeInputError': (arg: { from: number, to: number }) => LocalizedString
			/**
			 * {project} として保存されました。
			 */
			'projectSavedAs': (arg: { project: string }) => LocalizedString
			/**
			 * SUSファイルを読み込む際にエラーが発生しました
			 */
			'loadingSUSError': () => LocalizedString
			/**
			 * 譜面が自動保存されました
			 */
			'autoSaved': () => LocalizedString
			/**
			 * 譜面が保存されました
			 */
			'saved': () => LocalizedString
			/**
			 * アップロードするノーツが選択されていません
			 */
			'uploadNotSelectedError': () => LocalizedString
			/**
			 * タイトルを入力してください
			 */
			'inputTitlePrompt': () => LocalizedString
			/**
			 * 説明を入力してください
			 */
			'inputDescriptionPrompt': () => LocalizedString
			/**
			 * タイトルや説明を入力してください
			 */
			'inputEmptyError': () => LocalizedString
			/**
			 * アップロードしました
			 */
			'uploaded': () => LocalizedString
			/**
			 * アップロードに失敗しました
			 */
			'uploadFailed': () => LocalizedString
			/**
			 * 本当にエディターを閉じますか
			 */
			'exitConfirm': () => LocalizedString
			/**
			 * 不明なファイルタイプです
			 */
			'unknownFileType': () => LocalizedString
			/**
			 * ライブラリの読み込みに失敗しました。
			 */
			'loadingLibraryFailed': () => LocalizedString
			/**
			 * 設定を保存しました
			 */
			'preferencesSaved': () => LocalizedString
			/**
			 * 本当に削除しますか？
			 */
			'deleteConfirm': () => LocalizedString
		}
		'snapTo': {	
			/**
			 * {n}分音符
			 */
			'snap': (arg: { n: number }) => LocalizedString
			/**
			 * 分音符（1 ~ 1920）
			 */
			'snapWithRange': () => LocalizedString
			/**
			 * カスタム
			 */
			'custom': () => LocalizedString
		}
		'mutation': {	
			/**
			 * 更新
			 */
			'update': () => LocalizedString
			/**
			 * カット
			 */
			'cut': () => LocalizedString
			/**
			 * 削除
			 */
			'delete': () => LocalizedString
			/**
			 * 反転
			 */
			'flip': () => LocalizedString
			/**
			 * 移動
			 */
			'move': () => LocalizedString
			/**
			 * リサイズ
			 */
			'resize': () => LocalizedString
		}
		'dialog': {	
			/**
			 * BPM設定
			 */
			'bpmTitle': () => LocalizedString
			/**
			 * カスタム分音符
			 */
			'customSnappingTitle': () => LocalizedString
			/**
			 * 画像出力
			 */
			'imageTitle': () => LocalizedString
			/**
			 * ライブラリ
			 */
			'libraryTitle': () => LocalizedString
			/**
			 * 環境設定
			 */
			'preferencesTitle': () => LocalizedString
			/**
			 * 譜面一覧
			 */
			'projectsTitle': () => LocalizedString
			/**
			 * 追加
			 */
			'append': () => LocalizedString
			/**
			 * 変更
			 */
			'change': () => LocalizedString
			/**
			 * 出力
			 */
			'export': () => LocalizedString
			/**
			 * OK
			 */
			'ok': () => LocalizedString
			/**
			 * 新規作成
			 */
			'new': () => LocalizedString
			/**
			 * SUSファイルを開く
			 */
			'opensus': () => LocalizedString
		}
		'preferences': {	
			/**
			 * 自動保存の間隔（秒）
			 */
			'autosaveInterval': () => LocalizedString
			/**
			 * スクロールの早さ（倍）
			 */
			'scrollSpeed': () => LocalizedString
		}
		'modes': {	
			/**
			 * 選択
			 */
			'select': () => LocalizedString
			/**
			 * タップ
			 */
			'tap': () => LocalizedString
			/**
			 * スライド
			 */
			'slide': () => LocalizedString
			/**
			 * 中継点
			 */
			'mid': () => LocalizedString
			/**
			 * フリック
			 */
			'flick': () => LocalizedString
			/**
			 * クリティカル
			 */
			'critical': () => LocalizedString
			/**
			 * BPM
			 */
			'bpm': () => LocalizedString
		}
	}
}

export type Formatters = {}

type Param<P extends string> = `{${P}}`

type Params1<P1 extends string> =
	`${string}${Param<P1>}${string}`

type Params2<P1 extends string, P2 extends string> =
	`${string}${Param<P1>}${string}${Param<P2>}${string}`

type RequiredParams1<P1 extends string> =
	| Params1<P1>

type RequiredParams2<P1 extends string, P2 extends string> =
	| Params2<P1, P2>
	| Params2<P2, P1>
